baseURL = "https://silvanocerza.com/"
languageCode = "en-us"
title = "Silvano Cerza"
theme = "spectrum"
copyright = "© 2019 by Silvano Cerza. All rights are reserved."
enableRobotsTXT = "true"

[menu]
    [[menu.main]]
        name = "Blog"
        url = "/posts"
        weight = 1

    [[menu.main]]
        name = "Projects"
        url = "/projects"
        weight = 2

    [[menu.main]]
        name = "About"
        url = "/about"
        weight = 3

