baseURL = "https://silvanocerza.com/"
languageCode = "en-us"
title = "Silvano Cerza"
theme = "spectrum"
enableRobotsTXT = "true"
copyright = """
    © 2019 by Silvano Cerza.
    All content on this site is available under a
    <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">
    CC BY-SA 4.0 license
    </a>."""

[menu]
    [[menu.main]]
        name = "Blog"
        url = "/posts"
        weight = 1

    [[menu.main]]
        name = "Projects"
        url = "/projects"
        weight = 2

    [[menu.main]]
        name = "About"
        url = "/about"
        weight = 3

