baseURL = "https://silvanocerza.com/"
languageCode = "en-us"
title = "Silvano Cerza"
theme = "spectrum"
enableRobotsTXT = "true"
copyright = """
    © 2019 by Silvano Cerza.
    All content on this site is available under a
    <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">
    CC BY-SA 4.0 license
    </a>."""

[params]
    subtitle = "A person"
    mainSections = ["posts"]

[menu]
    [[menu.main]]
        name = "Blog"
        url = "/posts"
        weight = 1

    [[menu.main]]
        name = "Projects"
        url = "/projects"
        weight = 2

    [[menu.main]]
        name = "About"
        url = "/about"
        weight = 3

[privacy]
    [privacy.disqus]
        disable = false
    [privacy.googleAnalytics]
        anonymizeIP = true
        respectDoNotTrack = true
        useSessionStorage = true
    [privacy.instagram]
        simple = true
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = true
    [privacy.vimeo]
        disable = false
        simple = true
    [privacy.youtube]
        disable = false
        privacyEnhanced = true
