baseURL = "https://silvanocerza.com/"
languageCode = "en-us"
title = "Hey, I'm Silvano!"
theme = "hugo-ink"
enableRobotsTXT = "true"
copyright = "© Silvano Cerza CC BY-SA 4.0"

[markup]

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = "dracula"
tabWidth = 4

[params]
avatar = "https://gravatar.com/avatar/27349ff4290adc7e487ecfdc7feb0047?size=600"
subtitle = """
Writing code and other things
"""
author = "Silvano Cerza"
dateformat = "Jan 2, 2006"
# Light/dark mode
mode = "auto"

[[params.social]]
name = "github"
icon = "icons/github.svg"
url = "https://github.com/silvanocerza"

[[params.social]]
name = "linkedin"
icon = "icons/linkedin.svg"
url = "https://linkedin.com/in/silvanocerza"

[[params.social]]
name = "twitter"
icon = "icons/twitter.svg"
url = "https://twitter.com/SilvanoCerza"

[[params.social]]
name = "mastodon"
icon = "icons/mastodon.svg"
url = "https://mastodon.world/@silvanocerza"

[[params.social]]
name = "RSS"
icon = "icons/rss.svg"
url = "/index.xml"

[menu]

[[menu.main]]
name = "Resume"
url = "https://resume.silvanocerza.com/"
weight = 1

[[menu.main]]
name = "Talks"
url = "/talks"
weight = 2

[[menu.main]]
name = "What am up to now?"
url = "/now"
weight = 2

[privacy]

[privacy.disqus]
disable = true
skipAgree = false

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true

[privacy.instagram]
simple = true

[privacy.twitter]
disable = false
enableDNT = true
simple = true

[privacy.vimeo]
disable = false
simple = true

[privacy.youtube]
disable = false
privacyEnhanced = true
